[package]
name = "rust_by_example"
version = "0.1.0"
authors = ["zhiluniao <huangshunle_gxu@163.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
regex = "1"
lazy_static = "1.4.0"
chrono = "0.4"
rust-crypto = "^0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustc-serialize = "0.3"
qrcode = "0.11"
image = "0.23"
rayon = "1.3.0"
futures = "0.3.5" 